# Generated by Django 5.2.1 on 2025-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founded_by', models.CharField(max_length=200)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('coverage', models.CharField(max_length=500)),
                ('services', models.JSONField()),
                ('description', models.TextField()),
                ('remarks', models.TextField()),
                ('website', models.URLField()),
                ('contact_info', models.JSONField()),
                ('social_media', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NGO',
                'verbose_name_plural': 'NGOs',
                'ordering': ['name'],
            },
        ),
    ]
