# Generated by Django 4.2.6 on 2025-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerHospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_code', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('center', models.CharField(max_length=255)),
                ('pin_code', models.IntegerField()),
                ('geo_location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone_tel', models.BigIntegerField()),
                ('website', models.CharField(max_length=255)),
                ('review', models.FloatField(max_length=255)),
                ('review_count', models.IntegerField()),
                ('wheelchair', models.CharField(max_length=255)),
                ('blood_bank', models.CharField(max_length=255)),
                ('pathology', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('coords', models.CharField(max_length=255)),
                ('hospital_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('palliative_care', models.CharField(blank=True, max_length=25, null=True)),
                ('diagnosis_center', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CancerCenter',
        ),
    ]
