# Generated by Django 5.2.1 on 2025-06-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
