# Generated by Django 5.2.1 on 2025-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='slug',
            field=models.CharField(choices=[('risk', 'Risk Assessment'), ('insurance', 'Insurance & Coverage'), ('screening', 'Screening Process'), ('test_results', 'Test Results'), ('biopsies', 'Biopsy')], default='risk', max_length=50, unique=True),
        ),
    ]
