# Generated by Django 5.2.1 on 2025-06-28 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='caregivers/')),
                ('bio', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
